name: 🔍 Compliance Total — Multi-arquivos

on: [push, pull_request]

jobs:
  full-scan:
    name: 🔒 Escaneamento de Segurança Profundo
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: ⚙️ Instalar dependências
        run: |
          python -m pip install --upgrade pip

      - name: 🛡️ Validar arquivos JSON/YAML/TS
        run: python compliance/valida_compliance_lote.py
